### ISSUE TITLE
Plugin doesn't work with 'awesome window manager'

### ISSUE THREAD

**Issue by nanangarsyad** [sburlyaev/IDEA-Native-Terminal-Plugin#2]
Sorry for the silly question, I just wanted to make sure whether I did it correcly or not.
After I installed the plugin from jetbrain plugins repository, how did I open the native terminal?
Is it the same as the normal terminal? (`ALT` + `F12`)
I've been trying to activate it using the terminal button in Menu bar, in `Ctrl`+`Shift`+`A` popup menu, and also the `Native Terminal Plugin` is running
But from the look of it, seemed nothing happened, and I'm still using the default intellij terminal.

Here's the details
![peek 2018-04-06 08-11](https://user-images.githubusercontent.com/7588442/38399103-802f4e26-3972-11e8-8bbb-3fcf43c4fe67.gif)

nb, I'm using ubuntu 18.04 and awesomewm
Thank you

**Comment by sburlyaev** [comment]
Hi Nanang!
Usually you can open it using the terminal icon at the top tool bar. Looks like some environment issue.
I will test it on Android Studio on Ubuntu 18.04 and find a way how to solve this.
Thanks!

**Comment by sburlyaev** [comment]
Fixed in [55388a1](https://github.com/sburlyaev/IDEA-Native-Terminal-Plugin/commit/55388a1e10e4941f42b0e2a5bcfd499270741705). I've already uploaded the new build (v.0.1.1) to the JetBrains Plugins Repository, but moderation will take about two business days.
Thanks!

**Comment by nanangarsyad** [comment]
Well, thanks a  lot for you reply.
In my case it still not working. I'v read your commit 
https://github.com/sburlyaev/IDEA-Native-Terminal-Plugin/commit/55388a1e10e4941f42b0e2a5bcfd499270741705

My problem is, I use a few customization to my ubuntu startup script, starting from removing gdm. console mode (tty) mode login, and a few more. Because of that I couldn't launch gnome-terminal normally, as gnome need a few env variable that being set on startup squence by gdm. 
Here is a few article related about the problem I had [1](https://stackoverflow.com/questions/24735447/gnome-terminal-doesnt-work-maybe-because-of-locale-setting/33233222#33233222) [2](https://bbs.archlinux.org/viewtopic.php?id=222404) [3](https://wiki.gnome.org/Apps/Terminal/FAQ#Exit_status_10) [4](https://bbs.archlinux.org/viewtopic.php?id=206005)

...so, in the end to start gnome-terminal I had to follow the links mentioned above  andthen invoke gnome terminal using this command, `dbus-launch gnome-terminal`

Well I also put some comment to your commit, [here](https://github.com/sburlyaev/IDEA-Native-Terminal-Plugin/commit/55388a1e10e4941f42b0e2a5bcfd499270741705#r28646906)

Thanks yet again :)

**Comment by sburlyaev** [comment]
@nanangarsyad Nanang,
I've added some functionality to read a custom line from environment variable (it will be available in 0.1.2). To use this you need to set (export) environment variable `FAVORITE_TERMINAL=dbus-launch gnome-terminal`. Hope it will solve the issue.
Thanks!
